### ISSUE TITLE
compatibility with odk-central?

### ISSUE THREAD

**Issue by poVoq** [shivareddyiirs/QRealTime#11]
Has anyone tested this with the new odk-central server?
If it is using the same API as odk-briefcase it is probably not working.

Would be great if this and maybe the cool odata feed functionality could be made to work.

**Comment by shivareddyiirs** [comment]
Hi
Nobody has tested this with the odk-central server. Thanks for your feedback
Did you test with odk aggregate. is it working fine with your aggregate server?

**Comment by poVoq** [comment]
Currently contemplating which service to install (was previously on externally hosted Kobotoolbox), ODK central looks much friendlier for self-hosting, but this qgis plugin would really help to have working with it.

In general what kind of API does this plugin need? ODK collect is obviously working with ODK-Central, but ODK-Briefcase apparently not (yet).

**Comment by shivareddyiirs** [comment]
Our plugin is not a replacement for ODK collect.
It retrieve the submissions from aggregate server and also enable new form designing and uploading. (from GIS layer). (I think this is similar to ODK-briefcase)

I can try to support both odk aggregate and ODK central.
It seems you have good understanding regarding ODK central API. Can you suggest  some API reference document?

I would be glad to help you in modifying this plugin so that it can be used by you.

**Comment by poVoq** [comment]
I'll try to get ODK-Central working and will test it with this qGIS plugin. I doubt I will be able to actually make it work myself, but I will report back any findings.

**Comment by poVoq** [comment]
https://github.com/opendatakit/central-backend/blob/master/docs/api.md

**Comment by shivareddyiirs** [comment]
Any Updates @poVoq ?

**Comment by poVoq** [comment]
Sorry turned out that ODK-Central is after all a bit more complicated to get running via Docker than I thought. So this is on the backburner until further notice. But you can actually request access to the official sand-box servers if you just want to test it.

**Comment by shivareddyiirs** [comment]
I am closing this issue. I would try to include this feature once end user starts using ODK central
