### ISSUE TITLE
Use native QGIS networkAccessManager API in place of requests

### ISSUE THREAD

**Issue by joeflack4** [shivareddyiirs/QRealTime#18]
**Describe the bug**
After installing the plugin, the following message is received:
> The plugin is broken. Python said:
> **No module named requests**

**To Reproduce**
1. Open QGIS.
2. Open the plugin manager dialogue box and search for QRealTime.
3. Install

**Expected behavior**
No error message should be received.

**Screenshots**
<img width="984" alt="screen shot 2018-12-01 at 12 46 57 pm" src="https://user-images.githubusercontent.com/13045020/49331619-2d4c8f80-f56e-11e8-882c-29a6f157b426.png">

**Desktop (please complete the following information):**
- OS: MacOS 10.13.6
- QGIS 2.18.18

**Comment by shivareddyiirs** [comment]
Its strange because QGIS 2.18.x for windows comes with pre installed requests library! 
I think it is true for linux also. 
I have not tested this plugin in QGIS 2 in mac till now. 
One possible solutions: 
Use native QGIS networkManager API for http requests  in place of ‘requests’. Any help would be deeply appreciated.

**Comment by shivareddyiirs** [comment]
I found there is no such core library and waiting for this PR to be merged https://github.com/qgis/QGIS/pull/8440
